language: java
jdk:
  # only widely used one's also mindful about travis-ci resources
  - openjdk8
  - openjdk11

# whitelist
branches:
  only:
    - master
    #- api-v1  # since v1 API becoe absolute
